[development]
address = "localhost"
port = 5479
keep_alive = 600
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 5479
keep_alive = 600
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 5479
keep_alive = 600
log = "normal"
limits = { forms = 32768 }